name: Mend CLI Scan

on:
  workflow_dispatch

jobs:
  build:
        runs-on: ubuntu-latest

        steps:
        - uses: actions/checkout@v3
        # Add your package manager build here

        - name: Mend CLI Scan
          env:
            MEND_EMAIL: ${{secrets.MEND_EMAIL_BEN_TEST}}
            MEND_USER_KEY: ${{secrets.MEND_EMAIL_BEN_TEST_KEY}}
            MEND_URL: https://saas-eu.mend.io
          run: |
            echo Downloading Mend CLI
            curl -LJO https://downloads.mend.io/production/unified/latest/linux_amd64/mend && chmod +x mend 
            echo Start Mend CLI scan
            ./mend dep -u -s "beng_demo_gh//BenG//CSM_V2"
            #./mend code -s "beng_demo_gh//BenG//CSM_V1" --snippet-size 0
            #./mend image ubuntu:latest --scope "beng_demo_gh//BenG//CSM_V1"
